version: "2"

services:
  lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    restart: always
    image: postgres:9.6
    env_file: .env
    volumes:
      - db_data_quioskocortez:/var/lib/postgresql/data/pgdata

  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
      - ./static_cdn:/static_cdn
    expose: 
      - "8000"
    # ports:
    #   - "7000:5000"
    depends_on:
      - db
      - lb

volumes:
  db_data_quioskocortez:
    external: true